FROM node:11-alpine

WORKDIR /usr/src/app

ARG NODE_ENV=production

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
RUN npm install --silent

COPY . /usr/src/app


RUN npm run postinstall